services:
  frontend:
    image: ghcr.io/paulbeka/finance-frontend:latest
    container_name: finance_frontend
    restart: always
    ports:
      - "80:80"

  backend:
    image: ghcr.io/paulbeka/finance-backend:latest
    container_name: finance_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
